[package]
name = "wot"
version = "0.2.0"
edition = "2021"
description = "Web of Things (WoT)"
license = "MIT"
repository = "https://github.com/wot-rust/wot"
keywords = ["wot", "WebofThings"]

[dependencies]
wot-td = "0.2.1"
wot-serve = "0.3.1"
